language: python
python:
    - 3.7
install:
    - pip install -e . # install package + test dependencies
    - pip install codecov
    - pip install pytest-cov
script: pytest --cov=codecov
after_success:
    - codecov
